Django/Introducion/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    
    path('create/', BlogCreateView.as_view(), name="create"),
    
    #<int:pk>/ -> hace referencia al id de cada post
    path('<int:pk>/', BlogDetailView.as_view(), name ="detail" ),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name= "update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name= "delete")
]

Django/Introducion/core/urls.py
from django.contrib import admin
from django.urls import path, include
#Se importan las vistas en core
from .views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',HomeView.as_view(), name="home"),
    
    path('blog/', include('blog.urls', namespace='blog'))
]

Django/Introducion/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250)
    content=models.TextField()
    
    def __str__(self):
        return self.title
        

Django/Introducion/blog/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title', 'content')
        

Django/Introducion/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy
# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request, 'blog_list.html', context)
    
class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context={
            'form':form
        }
        return render(request, 'blog_create.html',context)
    
    def post(self, request, *args, **kwargs):
        if request.method == "POST":
           form = PostCreateForm(request.POST)
           if form.is_valid():
               title = form.cleaned_data.get('title')
               content = form.cleaned_data.get('content') 
               
               p, created = Post.objects.get_or_create(title=title, content=content)
               p.save()
               return redirect('blog:home')
               
        context={
            
        }

class BlogDetailView(View):
    def get(self, request,pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context={
             'post':post   
        }
            
        return render(request, 'blog_detail.html', context)

class BlogUpdateView(UpdateView):
    model=Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'
    
    def get_success_url(self):
       pk = self.kwargs['pk']
       return reverse_lazy('blog:detail',kwargs={'pk':pk})
   
class BlogDeleteView(DeleteView):
    model=Post
    template_name='blog_delete.html'
    success_url = reverse_lazy('blog:home')

Django/Introducion/core/views.py
#Se crean vistas
from django.views.generic import View
from django.shortcuts import render

#Vistas de clases
class HomeView(View):
    def get(self, request, *args,**kwargs):
        context={
            
        }
        return render(request, 'index.html', context)
        

Django/Introducion/templates/base.html
{% load static tailwind_tags %}
<html lang="en">
<head>
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

Django/Introducion/templates/blog_create.html
<form method = "POST">
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <button type= "submit"> submit </button>
</form>

Django/Introducion/templates/blog_delete.html
Are you sure?
<form method = "POST">
    {% csrf_token %}
    <br>
    <button type= "submit"> delete </button>
</form>

Django/Introducion/templates/blog_detail.html
detail
<br>

{{post.title}}
<br>
{{post.content}}

Django/Introducion/templates/blog_list.html
{% extends "base.html" %}
{% block content %}
blog list
<br>
{%for post in posts%}
<a href="{% url "blog:detail" post.id %}"> {{post.title}} </a>
<a href= "{% url "blog:update" post.id %}"> update </a>
<a href= "{% url "blog:delete" post.id %}"> delete </a>
<br>
{%endfor%}
<br>
<a type="button" href="{% url "blog:create" %}">Create </a>
<br>
{% endblock content %}

Django/Introducion/templates/blog_update.html
<form method = "POST">
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <button type= "submit"> Update </button>
</form>

Django/Introducion/templates/index.html
{% extends "base.html" %}
{% block content %}hola, visita mi <a class ="text-blue-500" href="{% url 'blog:home' %}"> blog aquí  </a>{% endblock content %}

Django/Introducion/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>